# Generated by Django 5.1.2 on 2024-11-20 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias_costos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='gastosOperacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('referencia', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='planNegocio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('autor', models.CharField(max_length=90)),
                ('problematica', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tipoInversionInicial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='inversionInicial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seccion', models.CharField(max_length=100)),
                ('importe', models.IntegerField()),
                ('planNegocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.plannegocio')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.tipoinversioninicial')),
            ],
        ),
        migrations.CreateModel(
            name='IndicadoresMacro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoCambio', models.DecimalField(decimal_places=3, max_digits=10)),
                ('inflacionAnual', models.DecimalField(decimal_places=3, max_digits=10)),
                ('tasaInteresDeuda', models.DecimalField(decimal_places=3, max_digits=10)),
                ('tasaInteresInversiones', models.DecimalField(decimal_places=3, max_digits=10)),
                ('tasaImpuesto', models.IntegerField()),
                ('ptu', models.IntegerField()),
                ('diasporMes', models.IntegerField()),
                ('planNegocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.plannegocio')),
            ],
        ),
        migrations.CreateModel(
            name='detalleInversionInicial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('elemento', models.CharField(max_length=100)),
                ('importe', models.IntegerField()),
                ('vida_util', models.IntegerField(null=True)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.inversioninicial')),
                ('planNegocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.plannegocio')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.tipoinversioninicial')),
            ],
        ),
        migrations.CreateModel(
            name='depreciacionMensual',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('depreciacionMensual', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('depreciacion_anio1', models.IntegerField(null=True)),
                ('depreciacion_anio2', models.IntegerField(null=True)),
                ('depreciacion_anio3', models.IntegerField(null=True)),
                ('depreciacion_anio4', models.IntegerField(null=True)),
                ('depreciacion_anio5', models.IntegerField(null=True)),
                ('valor_rescate', models.IntegerField(null=True)),
                ('inversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.detalleinversioninicial')),
                ('planNegocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.plannegocio')),
            ],
        ),
        migrations.CreateModel(
            name='ComposicionFinanciamiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('capitalSocial', models.IntegerField()),
                ('deuda', models.IntegerField()),
                ('planNegocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.plannegocio')),
            ],
        ),
        migrations.CreateModel(
            name='prestamo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('periodoCapitalizacion', models.IntegerField(null=True)),
                ('tasaInteresMensual', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('periodosAmortizacion', models.IntegerField(null=True)),
                ('cuotaFijaMensual', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('planNegocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.plannegocio')),
            ],
        ),
        migrations.CreateModel(
            name='Producto_servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('planNegocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.plannegocio')),
            ],
        ),
        migrations.CreateModel(
            name='PrecioVenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('planNegocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.plannegocio')),
                ('producto_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.producto_servicio')),
            ],
        ),
        migrations.CreateModel(
            name='costosVenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anio1', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('anio2', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('anio3', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('anio4', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('anio5', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('planNegocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.plannegocio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.producto_servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Costo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('costo', models.DecimalField(decimal_places=3, max_digits=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.categorias_costos')),
                ('planNegocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.plannegocio')),
                ('producto_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.producto_servicio')),
            ],
        ),
        migrations.CreateModel(
            name='proyeccionVentas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('ventas_mensuales', models.JSONField()),
                ('planNegocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.plannegocio')),
                ('producto_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.producto_servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Supuesto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('porcentaje_ventas_inventario', models.IntegerField()),
                ('variacion_porcentaje_ventas_credito', models.IntegerField()),
                ('ptu_se_paga_al_siguiente_ano', models.IntegerField()),
                ('isr_se_paga_al_siguiente_mes', models.IntegerField()),
                ('planNegocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.plannegocio')),
            ],
        ),
        migrations.CreateModel(
            name='VariacionAnual',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('porcentaje', models.IntegerField()),
                ('planNegocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.plannegocio')),
            ],
        ),
        migrations.CreateModel(
            name='VentaDiaria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ventas_por_dia', models.IntegerField()),
                ('planNegocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.plannegocio')),
                ('producto_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.producto_servicio')),
            ],
        ),
        migrations.CreateModel(
            name='ventasMes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anio1', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('anio2', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('anio3', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('anio4', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('anio5', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('planNegocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.plannegocio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.producto_servicio')),
            ],
        ),
    ]
