# Generated by Django 4.1.7 on 2024-06-21 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='planNegocio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('autor', models.CharField(max_length=90)),
                ('problematica', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='inversionInicial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seccion', models.CharField(max_length=100)),
                ('importe', models.IntegerField()),
                ('planNegocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.plannegocio')),
            ],
        ),
        migrations.CreateModel(
            name='detalleInversionInicial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('elemento', models.CharField(max_length=100)),
                ('importe', models.IntegerField()),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.inversioninicial')),
            ],
        ),
    ]
