# Generated by Django 5.1.2 on 2024-11-06 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livePlan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='costosVenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anio1', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('anio2', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('anio3', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('anio4', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('anio5', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('planNegocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.plannegocio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.producto_servicio')),
            ],
        ),
    ]
