# Generated by Django 4.1.7 on 2024-09-02 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livePlan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costo',
            name='costo',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.CreateModel(
            name='proyeccionVentas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('ventas_mensuales', models.JSONField()),
                ('planNegocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.plannegocio')),
                ('producto_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.producto_servicio')),
            ],
        ),
        migrations.CreateModel(
            name='IndicadoresMacro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoCambio', models.DecimalField(decimal_places=3, max_digits=10)),
                ('inflacionAnual', models.DecimalField(decimal_places=3, max_digits=10)),
                ('tasaInteresDeuda', models.DecimalField(decimal_places=3, max_digits=10)),
                ('tasaInteresInversiones', models.DecimalField(decimal_places=3, max_digits=10)),
                ('tasaImpuesto', models.IntegerField()),
                ('ptu', models.IntegerField()),
                ('diasporMes', models.IntegerField()),
                ('planNegocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.plannegocio')),
            ],
        ),
        migrations.CreateModel(
            name='FinanciamientoInversiones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('capitalSocial', models.IntegerField()),
                ('deuda', models.IntegerField()),
                ('planNegocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.plannegocio')),
            ],
        ),
    ]
