# Generated by Django 5.1.2 on 2024-11-13 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livePlan', '0002_costosventa'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoInversionProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
    ]
