# Generated by Django 4.1.7 on 2024-09-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livePlan', '0002_alter_costo_costo_proyeccionventas_indicadoresmacro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleinversioninicial',
            name='vida_util',
            field=models.IntegerField(null=True),
        ),
    ]
