# Generated by Django 5.1.2 on 2024-11-13 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livePlan', '0003_tipoinversionproducto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tipoInversionProducto',
            new_name='tipoInversionInicial',
        ),
    ]
