# Generated by Django 4.1.7 on 2024-09-09 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livePlan', '0003_detalleinversioninicial_vida_util'),
    ]

    operations = [
        migrations.CreateModel(
            name='depreciacionMensual',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('depreciacionMensual', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('depreciacion_anio1', models.IntegerField(null=True)),
                ('depreciacion_anio2', models.IntegerField(null=True)),
                ('depreciacion_anio3', models.IntegerField(null=True)),
                ('depreciacion_anio4', models.IntegerField(null=True)),
                ('depreciacion_anio5', models.IntegerField(null=True)),
                ('valor_rescate', models.IntegerField(null=True)),
                ('inversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.detalleinversioninicial')),
                ('planNegocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.plannegocio')),
            ],
        ),
    ]
