# Generated by Django 5.1.2 on 2024-11-13 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livePlan', '0004_rename_tipoinversionproducto_tipoinversioninicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversioninicial',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='livePlan.tipoinversioninicial'),
            preserve_default=False,
        ),
    ]
