# Generated by Django 4.1.7 on 2024-09-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livePlan', '0004_depreciacionmensual'),
    ]

    operations = [
        migrations.CreateModel(
            name='gastosOperacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('referencia', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
            ],
        ),
    ]
