# Generated by Django 4.1.7 on 2024-09-17 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livePlan', '0005_gastosoperacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComposicionFinanciamiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('capitalSocial', models.IntegerField()),
                ('deuda', models.IntegerField()),
                ('planNegocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.plannegocio')),
            ],
        ),
    ]
