# Generated by Django 4.1.7 on 2024-09-25 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livePlan', '0007_ventasmes'),
    ]

    operations = [
        migrations.CreateModel(
            name='prestamo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('periodoCapitalizacion', models.IntegerField()),
                ('tasaInteresMensual', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('periodosAmortizacion', models.IntegerField()),
                ('cuotaFijaMensual', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('planNegocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livePlan.plannegocio')),
            ],
        ),
    ]
